"""Add project model

Revision ID: cd0fddd8b795
Revises: daf4ee3e38a7
Create Date: 2026-07-15 15:43:24.014536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0fddd8b795'
down_revision = 'daf4ee3e38a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('projects_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('projects_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
